// AUTO-GENERATED by vite.config.ts — do not edit manually.
// Rebuilt on every `npm run dev` / `npm run build`.

export interface StaticQuestion {
  text: string;
  options: [string, string, string, string];
  correctAnswerIndex: number;
}

export const QUESTIONS_BY_DEPT: Record<string, Record<string, StaticQuestion[]>> = {
  "Civil": {
    "Question Bank": [
      { text: "What is the best description of 'Portland Cement'?", options: ["The most common type of cement in general use around the world", "A synthetic polymer used in road marking", "A natural stone used in masonry", "A type of reinforced steel"], correctAnswerIndex: 0 },
      { text: "What is the best description of 'Curing'?", options: ["The process of maintaining adequate moisture and temperature in concrete", "The excavation of soil for foundations", "The initial mixing of water and cement", "The process of bending steel rebars"], correctAnswerIndex: 0 },
      { text: "What is the best description of 'Slump Test'?", options: ["An empirical test that measures the workability of fresh concrete", "A test to determine the compressive strength of hardened concrete", "A test to measure the tensile strength of steel", "A test for soil compaction"], correctAnswerIndex: 0 },
      { text: "What is the best description of 'Reinforced Concrete'?", options: ["Concrete that has been pre-stressed only", "Concrete without any coarse aggregates", "Concrete that is mixed with salt water", "Concrete in which steel is embedded to increase its tensile strength"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'Bending Moment'?", options: ["The measure of a material's elasticity", "The internal force that causes a member to twist", "The force acting parallel to the cross-section", "The reaction induced in a structural element when an external force or moment is applied to the element causing it to bend"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'Shear Force'?", options: ["A force that pulls a member apart", "A moment that causes twisting", "An internal force in a structural member that acts parallel to the cross-section", "The maximum load a column can carry"], correctAnswerIndex: 2 },
      { text: "What is the best description of 'Truss'?", options: ["A retaining wall system", "A type of deep foundation", "A solid continuous concrete slab", "A framework, typically consisting of triangles, supporting a roof, bridge, or other structure"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'Hooke's Law'?", options: ["The buoyant force equals the weight of displaced fluid", "The sum of all forces at a node is zero", "The strain in a solid is proportional to the applied stress within the elastic limit", "The total energy in a fluid system is constant"], correctAnswerIndex: 2 },
      { text: "What is the best description of 'Atterberg Limits'?", options: ["Basic measures of the critical water contents of a fine-grained soil (shrinkage, plastic, and liquid limits)", "The maximum bearing capacity of rock", "The limits of steel elongation", "The speed limits on a newly constructed highway"], correctAnswerIndex: 0 },
      { text: "What is the best description of 'Consolidation'?", options: ["The physical compaction of soil using heavy machinery", "The chemical hardening of cement", "The immediate settling of dry sand", "The process by which soils decrease in volume over time as water is squeezed out of the pores under load"], correctAnswerIndex: 3 }
    ],
    "IQ Games": [
      { text: "What is the best description of 'Bearing Capacity'?", options: ["The maximum height of a retaining wall", "The capacity of soil to support the loads applied to the ground", "The amount of water a soil can hold", "The tensile strength of an embedded pile"], correctAnswerIndex: 1 },
      { text: "What is the best description of 'Theodolite'?", options: ["A tool to measure the slump of concrete", "A heavy machine for compacting asphalt", "A precision optical instrument for measuring angles between designated visible points in the horizontal and vertical planes", "A device used to test the compressive strength of cylinders"], correctAnswerIndex: 2 },
      { text: "What is the best description of 'Camber'?", options: ["The transverse slope provided to the road surface to drain off rainwater", "The widening of a road at a curve", "The longitudinal gradient of a road", "The thickness of the pavement base course"], correctAnswerIndex: 0 },
      { text: "What is the best description of 'Superelevation'?", options: ["The banking of a roadway along a curve to counteract centrifugal force", "The raising of ground level for flood protection", "The highest point of a bridge arch", "The excessive vibration of a bridge deck"], correctAnswerIndex: 0 },
      { text: "What is the best description of 'Manning's Equation'?", options: ["A formula for calculating structural deflection", "An equation for soil settlement over time", "A chemical equation for cement hydration", "An empirical equation applying to uniform flow in open channels"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'Hydraulic Jump'?", options: ["The flow of water through soil pores", "A phenomenon in open channel flow where high velocity liquid abruptly slows and increases in depth", "The sudden failure of a dam", "The pumping of groundwater from a well"], correctAnswerIndex: 1 },
      { text: "Which of the following statements correctly defines 'Portland Cement'?", options: ["The most common type of cement in general use around the world", "A type of reinforced steel", "A natural stone used in masonry", "A synthetic polymer used in road marking"], correctAnswerIndex: 0 },
      { text: "Which of the following statements correctly defines 'Curing'?", options: ["The excavation of soil for foundations", "The process of bending steel rebars", "The initial mixing of water and cement", "The process of maintaining adequate moisture and temperature in concrete"], correctAnswerIndex: 3 },
      { text: "Which of the following statements correctly defines 'Slump Test'?", options: ["A test to measure the tensile strength of steel", "A test to determine the compressive strength of hardened concrete", "A test for soil compaction", "An empirical test that measures the workability of fresh concrete"], correctAnswerIndex: 3 },
      { text: "Which of the following statements correctly defines 'Reinforced Concrete'?", options: ["Concrete that has been pre-stressed only", "Concrete that is mixed with salt water", "Concrete without any coarse aggregates", "Concrete in which steel is embedded to increase its tensile strength"], correctAnswerIndex: 3 }
    ],
    "Career Questions": [
      { text: "Which of the following statements correctly defines 'Bending Moment'?", options: ["The reaction induced in a structural element when an external force or moment is applied to the element causing it to bend", "The measure of a material's elasticity", "The internal force that causes a member to twist", "The force acting parallel to the cross-section"], correctAnswerIndex: 0 },
      { text: "Which of the following statements correctly defines 'Shear Force'?", options: ["The maximum load a column can carry", "An internal force in a structural member that acts parallel to the cross-section", "A moment that causes twisting", "A force that pulls a member apart"], correctAnswerIndex: 1 },
      { text: "Which of the following statements correctly defines 'Truss'?", options: ["A solid continuous concrete slab", "A framework, typically consisting of triangles, supporting a roof, bridge, or other structure", "A type of deep foundation", "A retaining wall system"], correctAnswerIndex: 1 },
      { text: "Which of the following statements correctly defines 'Hooke's Law'?", options: ["The strain in a solid is proportional to the applied stress within the elastic limit", "The total energy in a fluid system is constant", "The buoyant force equals the weight of displaced fluid", "The sum of all forces at a node is zero"], correctAnswerIndex: 0 },
      { text: "Which of the following statements correctly defines 'Atterberg Limits'?", options: ["The limits of steel elongation", "The maximum bearing capacity of rock", "The speed limits on a newly constructed highway", "Basic measures of the critical water contents of a fine-grained soil (shrinkage, plastic, and liquid limits)"], correctAnswerIndex: 3 },
      { text: "Which of the following statements correctly defines 'Consolidation'?", options: ["The physical compaction of soil using heavy machinery", "The immediate settling of dry sand", "The process by which soils decrease in volume over time as water is squeezed out of the pores under load", "The chemical hardening of cement"], correctAnswerIndex: 2 },
      { text: "Which of the following statements correctly defines 'Bearing Capacity'?", options: ["The maximum height of a retaining wall", "The amount of water a soil can hold", "The tensile strength of an embedded pile", "The capacity of soil to support the loads applied to the ground"], correctAnswerIndex: 3 },
      { text: "Which of the following statements correctly defines 'Theodolite'?", options: ["A heavy machine for compacting asphalt", "A device used to test the compressive strength of cylinders", "A tool to measure the slump of concrete", "A precision optical instrument for measuring angles between designated visible points in the horizontal and vertical planes"], correctAnswerIndex: 3 },
      { text: "Which of the following statements correctly defines 'Camber'?", options: ["The longitudinal gradient of a road", "The thickness of the pavement base course", "The transverse slope provided to the road surface to drain off rainwater", "The widening of a road at a curve"], correctAnswerIndex: 2 },
      { text: "Which of the following statements correctly defines 'Superelevation'?", options: ["The excessive vibration of a bridge deck", "The banking of a roadway along a curve to counteract centrifugal force", "The raising of ground level for flood protection", "The highest point of a bridge arch"], correctAnswerIndex: 1 }
    ],
  },
  "Mechanical": {
    "Question Bank": [
      { text: "What is the standard SI unit of Force?", options: ["Watt", "Joule", "Pascal", "Newton"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Work?", options: ["Pascal", "Watt", "Joule", "Newton"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit of Power?", options: ["Joule", "Pascal", "Newton", "Watt"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Pressure?", options: ["Newton", "Joule", "Pascal", "Watt"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit of Stress?", options: ["Newton", "Joule", "Watt", "Pascal"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Frequency?", options: ["Joule", "Watt", "Newton", "Hertz"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Velocity?", options: ["N/m", "m/s^2", "m/s", "kg/m^3"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit of Acceleration?", options: ["m/s", "kg/m^3", "m/s^2", "N/m"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit of Density?", options: ["kg/m^3", "N/m", "m/s^2", "m/s"], correctAnswerIndex: 0 },
      { text: "What is the standard SI unit of Surface Tension?", options: ["kg/m^3", "m/s", "N/m", "m/s^2"], correctAnswerIndex: 2 }
    ],
    "IQ Games": [
      { text: "What is the standard SI unit of Dynamic Viscosity?", options: ["N/m", "m^2/s", "J/kg", "Pa.s"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Kinematic Viscosity?", options: ["J/kg", "N/m", "Pa.s", "m^2/s"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Specific Heat?", options: ["W/m^2", "W/(m.K)", "J/(kg.K)", "J/kg"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit of Thermal Conductivity?", options: ["J/kg", "W/m^2", "J/(kg.K)", "W/(m.K)"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Heat Flux?", options: ["W/m^2", "J/(kg.K)", "J/kg", "W/(m.K)"], correctAnswerIndex: 0 },
      { text: "What is the standard SI unit of Torque?", options: ["J/kg", "N.m", "W", "N/m"], correctAnswerIndex: 1 },
      { text: "What is the standard SI unit of Angular Velocity?", options: ["rad/s^2", "Hz", "m/s", "rad/s"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Angular Acceleration?", options: ["rad/s", "Hz", "rad/s^2", "m/s^2"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit of Moment of Inertia?", options: ["kg/m^3", "N.m", "kg.m", "kg.m^2"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit of Mass Flow Rate?", options: ["kg/s", "m^3/s", "N/s", "J/s"], correctAnswerIndex: 0 }
    ],
    "Career Questions": [
      { text: "What is primarily associated with the First Law of Thermodynamics?", options: ["Energy conservation", "Absolute zero", "Ideal gas behavior", "Entropy increase"], correctAnswerIndex: 0 },
      { text: "Which principle or concept is best described by: 'Energy conservation'?", options: ["First Law of Thermodynamics", "Pascal's Law", "Newton's Law of Cooling", "Boyle's Law"], correctAnswerIndex: 0 },
      { text: "What is primarily associated with the Second Law of Thermodynamics?", options: ["Energy conservation", "Ideal gas behavior", "Absolute zero", "Entropy increase"], correctAnswerIndex: 3 },
      { text: "Which principle or concept is best described by: 'Entropy increase'?", options: ["Newton's Law of Cooling", "Pascal's Law", "Second Law of Thermodynamics", "Boyle's Law"], correctAnswerIndex: 2 },
      { text: "What is primarily associated with the Zeroth Law of Thermodynamics?", options: ["Energy conservation", "Thermal equilibrium", "Entropy increase", "Absolute zero"], correctAnswerIndex: 1 },
      { text: "Which principle or concept is best described by: 'Thermal equilibrium'?", options: ["Boyle's Law", "Pascal's Law", "Zeroth Law of Thermodynamics", "Newton's Law of Cooling"], correctAnswerIndex: 2 },
      { text: "What is primarily associated with the Third Law of Thermodynamics?", options: ["Energy conservation", "Entropy increase", "Thermal equilibrium", "Absolute zero"], correctAnswerIndex: 3 },
      { text: "Which principle or concept is best described by: 'Absolute zero'?", options: ["Boyle's Law", "Pascal's Law", "Third Law of Thermodynamics", "Newton's Law of Cooling"], correctAnswerIndex: 2 },
      { text: "What is primarily associated with the Otto Cycle?", options: ["Steam power plants", "Compression ignition engines", "Spark ignition engines", "Gas turbines"], correctAnswerIndex: 2 },
      { text: "Which principle or concept is best described by: 'Spark ignition engines'?", options: ["Otto Cycle", "Boyle's Law", "Newton's Law of Cooling", "Pascal's Law"], correctAnswerIndex: 0 }
    ],
  },
  "Electrical": {
    "Question Bank": [
      { text: "What is the standard SI unit or primary formula for Capacitance?", options: ["Farad", "Henry", "Ohm", "Tesla"], correctAnswerIndex: 0 },
      { text: "What is the standard SI unit or primary formula for Inductance?", options: ["Farad", "Weber", "Henry", "Ohm"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit or primary formula for Magnetic Flux?", options: ["Henry", "Tesla", "Weber", "Gauss"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit or primary formula for Magnetic Flux Density?", options: ["Henry", "Tesla", "Weber", "Ampere/meter"], correctAnswerIndex: 1 },
      { text: "What is the standard SI unit or primary formula for Electrical Charge?", options: ["Ampere", "Volt", "Coulomb", "Joule"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit or primary formula for Ohm's Law?", options: ["P = V * I", "V = I * R", "V = L * (di/dt)", "Q = C * V"], correctAnswerIndex: 1 },
      { text: "What is the standard SI unit or primary formula for Kirchhoff's Current Law (KCL)?", options: ["The algebraic sum of currents entering a node is zero", "Voltage is directly proportional to current", "The sum of voltage drops around a loop is zero", "Power is the product of voltage and current"], correctAnswerIndex: 0 },
      { text: "What is the standard SI unit or primary formula for Kirchhoff's Voltage Law (KVL)?", options: ["The algebraic sum of voltages around a closed loop is zero", "Current is inversely proportional to resistance", "Energy cannot be created or destroyed", "The sum of currents entering a node is zero"], correctAnswerIndex: 0 },
      { text: "What is the standard SI unit or primary formula for Faraday's Law of Induction?", options: ["Current through a conductor between two points is directly proportional to the voltage", "The force between two point charges is proportional to the product of the charges", "The total charge of an isolated system remains constant", "A changing magnetic field induces an electromotive force (EMF)"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit or primary formula for Lenz's Law?", options: ["The direction of an induced current opposes the change that produced it", "The total power in a circuit equals the sum of power dissipated", "Like charges repel, opposite charges attract", "The magnetic field of a coil is proportional to its current"], correctAnswerIndex: 0 }
    ],
    "IQ Games": [
      { text: "What is the standard SI unit or primary formula for Capacitor?", options: ["Restricts the flow of alternating current", "Stores electrical energy in an electric field", "Stores electrical energy in a magnetic field", "Converts alternating current to direct current"], correctAnswerIndex: 1 },
      { text: "What is the standard SI unit or primary formula for Inductor?", options: ["Measures the potential difference in a circuit", "Stores electrical energy in a magnetic field", "Allows direct current to pass while blocking alternating current", "Stores electrical energy in an electric field"], correctAnswerIndex: 1 },
      { text: "What is the standard SI unit or primary formula for Diode?", options: ["Measures the resistance of a circuit", "Steps up or steps down AC voltages", "Amplifies weak electrical signals", "Allows current to flow primarily in only one direction"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit or primary formula for Transistor?", options: ["Stores energy permanently", "Converts DC to AC", "Generates magnetic fields for motors", "Can act as an amplifier or a switch"], correctAnswerIndex: 3 },
      { text: "What is the standard SI unit or primary formula for Transformer?", options: ["Stores large amounts of static electricity", "Converts electrical energy into mechanical energy", "Steps up or steps down alternating current (AC) voltages", "Converts direct current (DC) to alternating current (AC)"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit or primary formula for Real Power (Active Power)?", options: ["The power consumed only by inductors", "The vector sum of true and reactive power", "The power actually consumed by the resistive loads, measured in Watts", "The power that oscillates between source and reactive loads"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit or primary formula for Reactive Power?", options: ["The power lost as heat in transmission lines", "The total power delivered by the utility company", "The power temporarily stored in inductive or capacitive elements, measured in VAR", "The mechanical power output of a motor"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit or primary formula for Apparent Power?", options: ["The power consumed by a diode", "The power dissipated by resistors", "The vector sum of real and reactive power, measured in VA", "The ratio of real power to apparent power"], correctAnswerIndex: 2 },
      { text: "What is the standard SI unit or primary formula for Power Factor?", options: ["The ratio of real power to apparent power", "The efficiency of a transformer", "The difference between apparent and reactive power", "The total impedance of a circuit"], correctAnswerIndex: 0 },
      { text: "What is the standard SI unit or primary formula for Inverter?", options: ["Increases the voltage of a DC signal", "Converts direct current (DC) to alternating current (AC)", "Acts as a safety switch against overcurrent", "Converts alternating current (AC) to direct current (DC)"], correctAnswerIndex: 1 }
    ],
    "Career Questions": [
      { text: "Which of the following statements best describes Capacitance?", options: ["Farad", "Ohm", "Tesla", "Henry"], correctAnswerIndex: 0 },
      { text: "Which of the following statements best describes Inductance?", options: ["Henry", "Ohm", "Farad", "Weber"], correctAnswerIndex: 0 },
      { text: "Which of the following statements best describes Magnetic Flux?", options: ["Henry", "Gauss", "Weber", "Tesla"], correctAnswerIndex: 2 },
      { text: "Which of the following statements best describes Magnetic Flux Density?", options: ["Weber", "Ampere/meter", "Tesla", "Henry"], correctAnswerIndex: 2 },
      { text: "Which of the following statements best describes Electrical Charge?", options: ["Ampere", "Volt", "Coulomb", "Joule"], correctAnswerIndex: 2 },
      { text: "Which of the following statements best describes Ohm's Law?", options: ["V = I * R", "P = V * I", "V = L * (di/dt)", "Q = C * V"], correctAnswerIndex: 0 },
      { text: "Which of the following statements best describes Kirchhoff's Current Law (KCL)?", options: ["Voltage is directly proportional to current", "Power is the product of voltage and current", "The sum of voltage drops around a loop is zero", "The algebraic sum of currents entering a node is zero"], correctAnswerIndex: 3 },
      { text: "Which of the following statements best describes Kirchhoff's Voltage Law (KVL)?", options: ["The algebraic sum of voltages around a closed loop is zero", "The sum of currents entering a node is zero", "Energy cannot be created or destroyed", "Current is inversely proportional to resistance"], correctAnswerIndex: 0 },
      { text: "Which of the following statements best describes Faraday's Law of Induction?", options: ["Current through a conductor between two points is directly proportional to the voltage", "A changing magnetic field induces an electromotive force (EMF)", "The force between two point charges is proportional to the product of the charges", "The total charge of an isolated system remains constant"], correctAnswerIndex: 1 },
      { text: "Which of the following statements best describes Lenz's Law?", options: ["The direction of an induced current opposes the change that produced it", "The total power in a circuit equals the sum of power dissipated", "The magnetic field of a coil is proportional to its current", "Like charges repel, opposite charges attract"], correctAnswerIndex: 0 }
    ],
  },
  "Architecture": {
    "Question Bank": [
      { text: "What does CAD stand for in architecture? ( 1)", options: ["Computer Aided Design", "Creative Art Drawing", "Civil Analysis Data", "Construction Aid Device"], correctAnswerIndex: 0 },
      { text: "Which material is commonly used for structural frameworks? ( 2)", options: ["Glass", "Steel", "Plastic", "Rubber"], correctAnswerIndex: 1 },
      { text: "What is the purpose of a blueprint? ( 3)", options: ["Decoration", "Construction planning", "Painting guide", "Marketing"], correctAnswerIndex: 1 },
      { text: "Which scale is commonly used in architectural drawings? ( 4)", options: ["1:100", "1:1", "10:1", "100:1"], correctAnswerIndex: 0 },
      { text: "What is a load-bearing wall? ( 5)", options: ["Decorative wall", "Wall that carries weight", "Glass wall", "Temporary wall"], correctAnswerIndex: 1 },
      { text: "Which software is widely used by architects? ( 6)", options: ["Photoshop", "AutoCAD", "Excel", "Word"], correctAnswerIndex: 1 },
      { text: "What is sustainability in architecture? ( 7)", options: ["Using bright colors", "Eco-friendly design", "Tall buildings", "Cheap materials"], correctAnswerIndex: 1 },
      { text: "Which element provides vertical circulation? ( 8)", options: ["Door", "Window", "Staircase", "Wall"], correctAnswerIndex: 2 },
      { text: "What is a foundation in construction? ( 9)", options: ["Roof", "Base structure", "Window frame", "Interior design"], correctAnswerIndex: 1 },
      { text: "What does HVAC stand for? ( 10)", options: ["Heating Ventilation Air Conditioning", "High Value Area Control", "Heat Volume Air Control", "None"], correctAnswerIndex: 0 }
    ],
    "IQ Games": [
      { text: "What does CAD stand for in architecture? ( 11)", options: ["Computer Aided Design", "Creative Art Drawing", "Civil Analysis Data", "Construction Aid Device"], correctAnswerIndex: 0 },
      { text: "Which material is commonly used for structural frameworks? ( 12)", options: ["Glass", "Steel", "Plastic", "Rubber"], correctAnswerIndex: 1 },
      { text: "What is the purpose of a blueprint? ( 13)", options: ["Decoration", "Construction planning", "Painting guide", "Marketing"], correctAnswerIndex: 1 },
      { text: "Which scale is commonly used in architectural drawings? ( 14)", options: ["1:100", "1:1", "10:1", "100:1"], correctAnswerIndex: 0 },
      { text: "What is a load-bearing wall? ( 15)", options: ["Decorative wall", "Wall that carries weight", "Glass wall", "Temporary wall"], correctAnswerIndex: 1 },
      { text: "Which software is widely used by architects? ( 16)", options: ["Photoshop", "AutoCAD", "Excel", "Word"], correctAnswerIndex: 1 },
      { text: "What is sustainability in architecture? ( 17)", options: ["Using bright colors", "Eco-friendly design", "Tall buildings", "Cheap materials"], correctAnswerIndex: 1 },
      { text: "Which element provides vertical circulation? ( 18)", options: ["Door", "Window", "Staircase", "Wall"], correctAnswerIndex: 2 },
      { text: "What is a foundation in construction? ( 19)", options: ["Roof", "Base structure", "Window frame", "Interior design"], correctAnswerIndex: 1 },
      { text: "What does HVAC stand for? ( 20)", options: ["Heating Ventilation Air Conditioning", "High Value Area Control", "Heat Volume Air Control", "None"], correctAnswerIndex: 0 }
    ],
    "Career Questions": [
      { text: "What does CAD stand for in architecture? ( 21)", options: ["Computer Aided Design", "Creative Art Drawing", "Civil Analysis Data", "Construction Aid Device"], correctAnswerIndex: 0 },
      { text: "Which material is commonly used for structural frameworks? ( 22)", options: ["Glass", "Steel", "Plastic", "Rubber"], correctAnswerIndex: 1 },
      { text: "What is the purpose of a blueprint? ( 23)", options: ["Decoration", "Construction planning", "Painting guide", "Marketing"], correctAnswerIndex: 1 },
      { text: "Which scale is commonly used in architectural drawings? ( 24)", options: ["1:100", "1:1", "10:1", "100:1"], correctAnswerIndex: 0 },
      { text: "What is a load-bearing wall? ( 25)", options: ["Decorative wall", "Wall that carries weight", "Glass wall", "Temporary wall"], correctAnswerIndex: 1 },
      { text: "Which software is widely used by architects? ( 26)", options: ["Photoshop", "AutoCAD", "Excel", "Word"], correctAnswerIndex: 1 },
      { text: "What is sustainability in architecture? ( 27)", options: ["Using bright colors", "Eco-friendly design", "Tall buildings", "Cheap materials"], correctAnswerIndex: 1 },
      { text: "Which element provides vertical circulation? ( 28)", options: ["Door", "Window", "Staircase", "Wall"], correctAnswerIndex: 2 },
      { text: "What is a foundation in construction? ( 29)", options: ["Roof", "Base structure", "Window frame", "Interior design"], correctAnswerIndex: 1 },
      { text: "What does HVAC stand for? ( 30)", options: ["Heating Ventilation Air Conditioning", "High Value Area Control", "Heat Volume Air Control", "None"], correctAnswerIndex: 0 }
    ],
  },
  "Pharmacy": {
    "Question Bank": [
      { text: "What does OTC stand for in pharmacy?", options: ["Over The Counter", "Over Total Cost", "Only Tested Compound", "Oral Treatment Course"], correctAnswerIndex: 0 },
      { text: "Which organ is primarily responsible for drug metabolism?", options: ["Kidney", "Liver", "Lung", "Heart"], correctAnswerIndex: 1 },
      { text: "What does the abbreviation 'bid' mean on a prescription?", options: ["Once daily", "Twice daily", "Three times daily", "Four times daily"], correctAnswerIndex: 1 },
      { text: "Which route of drug administration has the fastest onset of action?", options: ["Oral", "Sublingual", "Intravenous", "Intramuscular"], correctAnswerIndex: 2 },
      { text: "What is the brand name of paracetamol in most countries?", options: ["Brufen", "Tylenol/Panadol", "Aspirin", "Ibuprofen"], correctAnswerIndex: 1 },
      { text: "Which vitamin is also known as ascorbic acid?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctAnswerIndex: 2 },
      { text: "What does 'Rx' symbol on a prescription mean?", options: ["Recommended", "Take/Prescription required", "Refill", "Restricted"], correctAnswerIndex: 1 },
      { text: "Which class of drugs reduces fever?", options: ["Antibiotics", "Antipyretics", "Antihistamines", "Antacids"], correctAnswerIndex: 1 },
      { text: "What is the normal adult dose of paracetamol per dose?", options: ["100 mg", "250 mg", "500-1000 mg", "2000 mg"], correctAnswerIndex: 2 },
      { text: "Which organ primarily excretes drugs from the body?", options: ["Liver", "Skin", "Kidney", "Lung"], correctAnswerIndex: 2 }
    ],
    "IQ Games": [
      { text: "What does 'tds' mean on a prescription?", options: ["Twice daily", "Three times daily", "Four times daily", "Once daily"], correctAnswerIndex: 1 },
      { text: "Aspirin belongs to which drug class?", options: ["Opioid", "NSAID", "Antibiotic", "Antifungal"], correctAnswerIndex: 1 },
      { text: "What is the antidote for paracetamol overdose?", options: ["Naloxone", "N-acetylcysteine", "Flumazenil", "Atropine"], correctAnswerIndex: 1 },
      { text: "Which type of drug requires a prescription to be dispensed?", options: ["OTC drug", "Prescription-only medicine (POM)", "Herbal supplement", "Vitamin tablet"], correctAnswerIndex: 1 },
      { text: "What does 'stat' mean in a medication order?", options: ["Slowly", "Immediately/at once", "Stop after 3 days", "Standard dose"], correctAnswerIndex: 1 },
      { text: "Which route delivers medication directly into the skin layers?", options: ["Intravenous", "Intramuscular", "Intradermal", "Subcutaneous"], correctAnswerIndex: 2 },
      { text: "What is bioavailability?", options: ["Speed of drug excretion", "Fraction of drug that reaches systemic circulation unchanged", "Drug toxicity level", "Drug solubility in water"], correctAnswerIndex: 1 },
      { text: "Penicillin is an example of which drug class?", options: ["Antifungal", "Antiviral", "Antibiotic", "Antiparasitic"], correctAnswerIndex: 2 },
      { text: "Which part of a tablet coating protects the drug from stomach acid?", options: ["Film coat", "Sugar coat", "Enteric coat", "Color coat"], correctAnswerIndex: 2 },
      { text: "What does 'qid' mean on a prescription?", options: ["Once daily", "Twice daily", "Three times daily", "Four times daily"], correctAnswerIndex: 3 }
    ],
    "Career Questions": [
      { text: "Which drug is a common antihistamine for allergies?", options: ["Amoxicillin", "Cetirizine", "Metformin", "Omeprazole"], correctAnswerIndex: 1 },
      { text: "What is the half-life of a drug?", options: ["Time for drug to be fully excreted", "Time for drug concentration to reduce by half", "Time to reach peak effect", "Time of drug absorption"], correctAnswerIndex: 1 },
      { text: "Which type of insulin has the fastest onset?", options: ["Glargine", "NPH", "Regular insulin", "Rapid-acting (lispro/aspart)"], correctAnswerIndex: 3 },
      { text: "What does 'PRN' mean in prescriptions?", options: ["Per Regular Norm", "As needed", "Per Registered Nurse", "Post Recovery Note"], correctAnswerIndex: 1 },
      { text: "Which vitamin deficiency causes rickets?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctAnswerIndex: 3 },
      { text: "Metformin is used to treat which condition?", options: ["Hypertension", "Type 2 diabetes", "Asthma", "Depression"], correctAnswerIndex: 1 },
      { text: "What is the purpose of a drug expiry date?", options: ["Marketing requirement", "Guarantee of safety and potency up to that date", "Legal formality", "Packaging regulation"], correctAnswerIndex: 1 },
      { text: "Which type of formulation releases drug slowly over time?", options: ["Immediate release", "Sustained/Extended release", "Effervescent", "Dispersible"], correctAnswerIndex: 1 },
      { text: "What does 'sublingual' administration mean?", options: ["Swallowing whole", "Under the tongue", "Into the vein", "On the skin"], correctAnswerIndex: 1 },
      { text: "Salbutamol (albuterol) is used to treat which condition?", options: ["Diabetes", "Asthma", "Hypertension", "Infection"], correctAnswerIndex: 1 }
    ],
  },
  "Bioscience": {
    "Question Bank": [
      { text: "Q1: Cell Biology: What happens if Na+/K+ ATPase is inhibited in animal cells?", options: ["No effect on osmotic balance", "Cell swelling due to osmotic imbalance", "Immediate DNA damage", "Cell shrinkage due to ion loss"], correctAnswerIndex: 1 },
      { text: "Q2: Genetics: A mutation in the promoter region of a gene most likely affects:", options: ["Protein folding", "mRNA splicing", "Transcription initiation", "Translation termination"], correctAnswerIndex: 2 },
      { text: "Q3: Biochemistry: If Km increases while Vmax remains constant, it indicates:", options: ["Lower enzyme affinity", "Substrate depletion", "Higher enzyme affinity", "Enzyme denaturation"], correctAnswerIndex: 0 },
      { text: "Q4: Molecular Biology: Which enzyme synthesizes RNA from DNA template?", options: ["Ligase", "Helicase", "RNA polymerase", "DNA polymerase"], correctAnswerIndex: 2 },
      { text: "Q5: Immunology: Memory B cells are important because they:", options: ["Enable faster secondary response", "Produce antibodies immediately", "Suppress immune response", "Destroy pathogens directly"], correctAnswerIndex: 0 },
      { text: "Q6: Microbiology: Gram-negative bacteria are resistant to penicillin mainly due to:", options: ["Thick peptidoglycan", "High mutation rate", "Lack of ribosomes", "Outer membrane barrier"], correctAnswerIndex: 3 },
      { text: "Q7: Physiology: Oxygen dissociation curve shifts right when:", options: ["pH increases", "Hemoglobin increases", "Temperature decreases", "CO2 increases"], correctAnswerIndex: 3 },
      { text: "Q8: Ecology: Carrying capacity refers to:", options: ["Growth rate of population", "Death rate only", "Migration rate", "Max population environment supports"], correctAnswerIndex: 3 },
      { text: "Q9: Evolution: Natural selection acts on:", options: ["Phenotype", "Chromosomes only", "DNA sequence directly", "Genotype only"], correctAnswerIndex: 0 },
      { text: "Q10: Biotechnology: PCR amplification requires:", options: ["Ligase enzyme", "Restriction enzymes", "DNA template, primers, Taq polymerase", "RNA polymerase"], correctAnswerIndex: 2 }
    ],
    "IQ Games": [
      { text: "Q11: Cell Biology: What happens if Na+/K+ ATPase is inhibited in animal cells?", options: ["Immediate DNA damage", "Cell shrinkage due to ion loss", "No effect on osmotic balance", "Cell swelling due to osmotic imbalance"], correctAnswerIndex: 3 },
      { text: "Q12: Genetics: A mutation in the promoter region of a gene most likely affects:", options: ["mRNA splicing", "Translation termination", "Transcription initiation", "Protein folding"], correctAnswerIndex: 2 },
      { text: "Q13: Biochemistry: If Km increases while Vmax remains constant, it indicates:", options: ["Higher enzyme affinity", "Substrate depletion", "Lower enzyme affinity", "Enzyme denaturation"], correctAnswerIndex: 2 },
      { text: "Q14: Molecular Biology: Which enzyme synthesizes RNA from DNA template?", options: ["RNA polymerase", "Ligase", "Helicase", "DNA polymerase"], correctAnswerIndex: 0 },
      { text: "Q15: Immunology: Memory B cells are important because they:", options: ["Destroy pathogens directly", "Produce antibodies immediately", "Suppress immune response", "Enable faster secondary response"], correctAnswerIndex: 3 },
      { text: "Q16: Microbiology: Gram-negative bacteria are resistant to penicillin mainly due to:", options: ["High mutation rate", "Lack of ribosomes", "Outer membrane barrier", "Thick peptidoglycan"], correctAnswerIndex: 2 },
      { text: "Q17: Physiology: Oxygen dissociation curve shifts right when:", options: ["CO2 increases", "Temperature decreases", "Hemoglobin increases", "pH increases"], correctAnswerIndex: 0 },
      { text: "Q18: Ecology: Carrying capacity refers to:", options: ["Max population environment supports", "Growth rate of population", "Migration rate", "Death rate only"], correctAnswerIndex: 0 },
      { text: "Q19: Evolution: Natural selection acts on:", options: ["DNA sequence directly", "Genotype only", "Chromosomes only", "Phenotype"], correctAnswerIndex: 3 },
      { text: "Q20: Biotechnology: PCR amplification requires:", options: ["Restriction enzymes", "DNA template, primers, Taq polymerase", "RNA polymerase", "Ligase enzyme"], correctAnswerIndex: 1 }
    ],
    "Career Questions": [
      { text: "Q21: Cell Biology: What happens if Na+/K+ ATPase is inhibited in animal cells?", options: ["No effect on osmotic balance", "Immediate DNA damage", "Cell shrinkage due to ion loss", "Cell swelling due to osmotic imbalance"], correctAnswerIndex: 3 },
      { text: "Q22: Genetics: A mutation in the promoter region of a gene most likely affects:", options: ["mRNA splicing", "Transcription initiation", "Protein folding", "Translation termination"], correctAnswerIndex: 1 },
      { text: "Q23: Biochemistry: If Km increases while Vmax remains constant, it indicates:", options: ["Enzyme denaturation", "Lower enzyme affinity", "Higher enzyme affinity", "Substrate depletion"], correctAnswerIndex: 1 },
      { text: "Q24: Molecular Biology: Which enzyme synthesizes RNA from DNA template?", options: ["DNA polymerase", "RNA polymerase", "Helicase", "Ligase"], correctAnswerIndex: 1 },
      { text: "Q25: Immunology: Memory B cells are important because they:", options: ["Destroy pathogens directly", "Produce antibodies immediately", "Suppress immune response", "Enable faster secondary response"], correctAnswerIndex: 3 },
      { text: "Q26: Microbiology: Gram-negative bacteria are resistant to penicillin mainly due to:", options: ["Lack of ribosomes", "Thick peptidoglycan", "High mutation rate", "Outer membrane barrier"], correctAnswerIndex: 3 },
      { text: "Q27: Physiology: Oxygen dissociation curve shifts right when:", options: ["pH increases", "Temperature decreases", "CO2 increases", "Hemoglobin increases"], correctAnswerIndex: 2 },
      { text: "Q28: Ecology: Carrying capacity refers to:", options: ["Migration rate", "Death rate only", "Max population environment supports", "Growth rate of population"], correctAnswerIndex: 2 },
      { text: "Q29: Evolution: Natural selection acts on:", options: ["Phenotype", "Genotype only", "DNA sequence directly", "Chromosomes only"], correctAnswerIndex: 0 },
      { text: "Q30: Biotechnology: PCR amplification requires:", options: ["Restriction enzymes", "Ligase enzyme", "RNA polymerase", "DNA template, primers, Taq polymerase"], correctAnswerIndex: 3 }
    ],
  },
  "Allied Health Sciences": {
    "Question Bank": [
      { text: "What is the primary function of red blood cells? ( 1)", options: ["Transport oxygen", "Fight infection", "Clot blood", "Produce hormones"], correctAnswerIndex: 0 },
      { text: "Which organ filters blood in the human body? ( 2)", options: ["Heart", "Liver", "Kidney", "Lungs"], correctAnswerIndex: 2 },
      { text: "What is the normal body temperature in Celsius? ( 3)", options: ["35°C", "36-37°C", "38°C", "39°C"], correctAnswerIndex: 1 },
      { text: "Which vitamin is produced when skin is exposed to sunlight? ( 4)", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctAnswerIndex: 3 },
      { text: "What is the unit of blood pressure? ( 5)", options: ["mmHg", "cmHg", "kg", "Pa"], correctAnswerIndex: 0 },
      { text: "Which system controls body movement? ( 6)", options: ["Digestive", "Nervous", "Respiratory", "Circulatory"], correctAnswerIndex: 1 },
      { text: "What is the function of platelets? ( 7)", options: ["Oxygen transport", "Clotting", "Digestion", "Immunity"], correctAnswerIndex: 1 },
      { text: "Which organ is responsible for detoxification? ( 8)", options: ["Heart", "Liver", "Brain", "Kidney"], correctAnswerIndex: 1 },
      { text: "What is the basic unit of life? ( 9)", options: ["Cell", "Tissue", "Organ", "Atom"], correctAnswerIndex: 0 },
      { text: "Which gas do humans inhale for respiration? ( 10)", options: ["CO2", "O2", "N2", "H2"], correctAnswerIndex: 1 }
    ],
    "IQ Games": [
      { text: "What is the primary function of red blood cells? ( 11)", options: ["Transport oxygen", "Fight infection", "Clot blood", "Produce hormones"], correctAnswerIndex: 0 },
      { text: "Which organ filters blood in the human body? ( 12)", options: ["Heart", "Liver", "Kidney", "Lungs"], correctAnswerIndex: 2 },
      { text: "What is the normal body temperature in Celsius? ( 13)", options: ["35°C", "36-37°C", "38°C", "39°C"], correctAnswerIndex: 1 },
      { text: "Which vitamin is produced when skin is exposed to sunlight? ( 14)", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctAnswerIndex: 3 },
      { text: "What is the unit of blood pressure? ( 15)", options: ["mmHg", "cmHg", "kg", "Pa"], correctAnswerIndex: 0 },
      { text: "Which system controls body movement? ( 16)", options: ["Digestive", "Nervous", "Respiratory", "Circulatory"], correctAnswerIndex: 1 },
      { text: "What is the function of platelets? ( 17)", options: ["Oxygen transport", "Clotting", "Digestion", "Immunity"], correctAnswerIndex: 1 },
      { text: "Which organ is responsible for detoxification? ( 18)", options: ["Heart", "Liver", "Brain", "Kidney"], correctAnswerIndex: 1 },
      { text: "What is the basic unit of life? ( 19)", options: ["Cell", "Tissue", "Organ", "Atom"], correctAnswerIndex: 0 },
      { text: "Which gas do humans inhale for respiration? ( 20)", options: ["CO2", "O2", "N2", "H2"], correctAnswerIndex: 1 }
    ],
    "Career Questions": [
      { text: "What is the primary function of red blood cells? ( 21)", options: ["Transport oxygen", "Fight infection", "Clot blood", "Produce hormones"], correctAnswerIndex: 0 },
      { text: "Which organ filters blood in the human body? ( 22)", options: ["Heart", "Liver", "Kidney", "Lungs"], correctAnswerIndex: 2 },
      { text: "What is the normal body temperature in Celsius? ( 23)", options: ["35°C", "36-37°C", "38°C", "39°C"], correctAnswerIndex: 1 },
      { text: "Which vitamin is produced when skin is exposed to sunlight? ( 24)", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctAnswerIndex: 3 },
      { text: "What is the unit of blood pressure? ( 25)", options: ["mmHg", "cmHg", "kg", "Pa"], correctAnswerIndex: 0 },
      { text: "Which system controls body movement? ( 26)", options: ["Digestive", "Nervous", "Respiratory", "Circulatory"], correctAnswerIndex: 1 },
      { text: "What is the function of platelets? ( 27)", options: ["Oxygen transport", "Clotting", "Digestion", "Immunity"], correctAnswerIndex: 1 },
      { text: "Which organ is responsible for detoxification? ( 28)", options: ["Heart", "Liver", "Brain", "Kidney"], correctAnswerIndex: 1 },
      { text: "What is the basic unit of life? ( 29)", options: ["Cell", "Tissue", "Organ", "Atom"], correctAnswerIndex: 0 },
      { text: "Which gas do humans inhale for respiration? ( 30)", options: ["CO2", "O2", "N2", "H2"], correctAnswerIndex: 1 }
    ],
  },
  "Nursing": {
    "Question Bank": [
      { text: "What is the normal adult body temperature in Celsius?", options: ["35°C", "36.5–37.5°C", "38.5°C", "40°C"], correctAnswerIndex: 1 },
      { text: "Which blood type is known as the universal donor?", options: ["AB+", "O+", "O-", "A-"], correctAnswerIndex: 2 },
      { text: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], correctAnswerIndex: 1 },
      { text: "What is the normal adult respiratory rate per minute?", options: ["6-10", "12-20", "22-30", "30-40"], correctAnswerIndex: 1 },
      { text: "What does BP stand for in nursing?", options: ["Body Proportion", "Blood Pressure", "Body Pulse", "Bone Position"], correctAnswerIndex: 1 },
      { text: "Which organ produces insulin?", options: ["Liver", "Kidney", "Pancreas", "Spleen"], correctAnswerIndex: 2 },
      { text: "What is the normal adult pulse rate per minute?", options: ["40-60", "60-100", "100-120", "120-140"], correctAnswerIndex: 1 },
      { text: "Which vitamin is produced when skin is exposed to sunlight?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctAnswerIndex: 3 },
      { text: "What is the largest organ of the human body?", options: ["Heart", "Liver", "Skin", "Lung"], correctAnswerIndex: 2 },
      { text: "Normal blood glucose fasting level is?", options: ["2-4 mmol/L", "4-7 mmol/L", "8-10 mmol/L", "10-12 mmol/L"], correctAnswerIndex: 1 }
    ],
    "IQ Games": [
      { text: "Which part of the heart pumps blood to the lungs?", options: ["Left ventricle", "Right ventricle", "Left atrium", "Right atrium"], correctAnswerIndex: 1 },
      { text: "What does IV stand for in medication administration?", options: ["Internal Vein", "Intravenous", "Intermediate Volume", "Intravascular"], correctAnswerIndex: 1 },
      { text: "Which position is used for patients in shock?", options: ["Sitting upright", "Trendelenburg", "Prone", "Lateral"], correctAnswerIndex: 1 },
      { text: "What is the universal precaution all nurses must take?", options: ["Wear gloves always", "Handwashing", "Use mask", "Double gloving"], correctAnswerIndex: 1 },
      { text: "Which nerve controls heart rate?", options: ["Femoral", "Radial", "Vagus", "Ulnar"], correctAnswerIndex: 2 },
      { text: "What does 'NPO' mean in nursing orders?", options: ["No Pain Observed", "Nothing by Mouth", "Normal Patient Outcome", "No Pressure Order"], correctAnswerIndex: 1 },
      { text: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], correctAnswerIndex: 2 },
      { text: "Normal urine output per hour for an adult is?", options: ["10-20 mL", "30-50 mL", "60-80 mL", "100 mL"], correctAnswerIndex: 1 },
      { text: "Which artery is used to check pulse at the wrist?", options: ["Brachial", "Carotid", "Radial", "Femoral"], correctAnswerIndex: 2 },
      { text: "What is the correct sequence of CPR compressions to breaths for adults?", options: ["15:2", "30:2", "20:1", "10:1"], correctAnswerIndex: 1 }
    ],
    "Career Questions": [
      { text: "Which electrolyte is most abundant inside body cells?", options: ["Sodium", "Chloride", "Potassium", "Calcium"], correctAnswerIndex: 2 },
      { text: "What is the normal SpO2 range for a healthy adult?", options: ["80-85%", "86-90%", "95-100%", "70-80%"], correctAnswerIndex: 2 },
      { text: "What does 'PRN' mean in medication orders?", options: ["Per Routine Needs", "As Needed", "Per Registered Nurse", "Post Recovery Note"], correctAnswerIndex: 1 },
      { text: "Which lobe of the brain controls movement?", options: ["Frontal", "Parietal", "Temporal", "Occipital"], correctAnswerIndex: 0 },
      { text: "A patient who cannot swallow should be given medications?", options: ["Orally", "Via nasogastric tube", "Rectally", "Sublingually"], correctAnswerIndex: 1 },
      { text: "What is the main function of red blood cells?", options: ["Fight infection", "Clot blood", "Carry oxygen", "Produce antibodies"], correctAnswerIndex: 2 },
      { text: "Which PPE is used to prevent droplet transmission?", options: ["Gloves", "Surgical mask", "N95 respirator", "Eye goggles"], correctAnswerIndex: 2 },
      { text: "What does 'ROM' stand for in physiotherapy?", options: ["Rate Of Movement", "Range of Motion", "Rotation of Muscle", "Rest on Mat"], correctAnswerIndex: 1 },
      { text: "How often should bed-ridden patients be repositioned to prevent bedsores?", options: ["Every 8 hours", "Every 4 hours", "Every 2 hours", "Every 30 minutes"], correctAnswerIndex: 2 },
      { text: "A patient with chest pain should first be?", options: ["Given water", "Placed in supine", "Given aspirin", "Seated upright and monitored"], correctAnswerIndex: 3 }
    ],
  },
  "Management of Science": {
    "Question Bank": [
      { text: "What is the best description or definition of: fundamental accounting equation?", options: ["Assets = Liabilities + Equity", "Assets = Liabilities - Equity", "Cash = Inflows - Outflows", "Revenue = Expenses + Profit"], correctAnswerIndex: 0 },
      { text: "What is the best description or definition of: Return on Investment (ROI)?", options: ["Gross Profit / Revenue", "Total Assets / Total Liabilities", "Net Profit / Cost of Investment", "Total Revenue - Total Expenses"], correctAnswerIndex: 2 },
      { text: "What is the best description or definition of: Balance Sheet?", options: ["A snapshot of a company's financial position at a specific point in time", "A record of all cash transactions", "A projection of future sales", "A summary of revenues and expenses over a period"], correctAnswerIndex: 0 },
      { text: "What is the best description or definition of: Income Statement?", options: ["A summary of revenues and expenses over a period", "A record of equity changes", "A breakdown of operating cash flows", "A snapshot of assets and liabilities"], correctAnswerIndex: 0 },
      { text: "What is the best description or definition of: Liquidity?", options: ["The profitability of a company over time", "The market share of a company", "The total amount of debt a company owes", "The ease with which an asset can be converted into cash"], correctAnswerIndex: 3 },
      { text: "What is the best description or definition of: Marketing Mix (4Ps)?", options: ["Planning, Production, Pricing, Placement", "Profit, Product, Priority, Penetration", "Product, Price, Place, Promotion", "People, Process, Physical Evidence, Packaging"], correctAnswerIndex: 2 },
      { text: "What is the best description or definition of: Market Segmentation?", options: ["Analyzing competitors' market share", "Combining multiple markets into one global strategy", "Dividing a market into distinct groups of buyers with different needs", "Setting different prices for the same product"], correctAnswerIndex: 2 },
      { text: "What is the best description or definition of: Brand Equity?", options: ["The cost of manufacturing a branded product", "The total monetary value of the company's physical assets", "The commercial value derived from consumer perception of the brand name", "The number of shares a company has issued"], correctAnswerIndex: 2 },
      { text: "What is the best description or definition of: SEO (Search Engine Optimization)?", options: ["Paying for top placement in search results", "Sending mass promotional emails to customers", "Improving a website to increase its visibility in search engines", "Creating physical billboards"], correctAnswerIndex: 2 },
      { text: "What is the best description or definition of: SWOT Analysis?", options: ["Strengths, Weaknesses, Opportunities, Threats", "Strategy, Workforce, Objectives, Tactics", "Sales, Wealth, Operations, Taxes", "Service, Warranty, Operations, Time"], correctAnswerIndex: 0 }
    ],
    "IQ Games": [
      { text: "What is the best description or definition of: Onboarding?", options: ["The termination of an employee's contract", "The annual performance review", "The process of integrating a new employee into an organization", "The process of interviewing candidates"], correctAnswerIndex: 2 },
      { text: "What is the best description or definition of: Performance Appraisal?", options: ["The regular review of an employee's job performance and overall contribution", "The process of union negotiation", "The process of calculating employee payroll", "The initial screening of job applicants"], correctAnswerIndex: 0 },
      { text: "What is the best description or definition of: Maslow's Hierarchy of Needs base level?", options: ["Esteem Needs", "Physiological Needs", "Self-Actualization", "Safety Needs"], correctAnswerIndex: 1 },
      { text: "What is the best description or definition of: Fringe Benefits?", options: ["Additional compensation provided to employees beyond their base salary", "The primary hourly wage paid to workers", "Penalties for poor employee performance", "Taxes paid by the employer to the government"], correctAnswerIndex: 0 },
      { text: "What is the best description or definition of: Turnover Rate?", options: ["The speed at which inventory is sold", "The percentage of job applicants hired", "The total revenue generated per employee", "The percentage of employees who leave an organization within a certain period"], correctAnswerIndex: 3 },
      { text: "What is the best description or definition of: Just-In-Time (JIT) Inventory?", options: ["Selling goods immediately after they are produced", "Ordering inventory once a year in bulk", "Keeping a large surplus of goods to prevent shortages", "Receiving goods only as they are needed in the production process"], correctAnswerIndex: 3 },
      { text: "What is the best description or definition of: Economic Order Quantity (EOQ)?", options: ["The ideal order quantity a company should purchase to minimize inventory costs", "The maximum amount of inventory a warehouse can hold", "The minimum price a supplier will accept", "The total number of orders placed in a year"], correctAnswerIndex: 0 },
      { text: "What is the best description or definition of: Six Sigma?", options: ["A financial strategy for managing debt", "An employee training program", "A six-step marketing plan", "A set of techniques and tools for process improvement and defect reduction"], correctAnswerIndex: 3 },
      { text: "What is the best description or definition of: Supply Chain Management?", options: ["The marketing of physical products", "The auditing of manufacturing expenses", "The process of hiring logistics personnel", "The management of the flow of goods and services from raw materials to final consumer"], correctAnswerIndex: 3 },
      { text: "What is the best description or definition of: Quality Control?", options: ["The process of increasing product prices", "The negotiation of supplier contracts", "The process of ensuring products meet specific standards and requirements", "The management of employee benefits"], correctAnswerIndex: 2 }
    ],
    "Career Questions": [
      { text: "What is the best description or definition of: Porter's Five Forces?", options: ["A framework for analyzing a company's competitive environment", "A method for calculating employee salaries", "A five-step product development cycle", "A framework for ethical decision making"], correctAnswerIndex: 0 },
      { text: "What is the best description or definition of: PESTLE Analysis?", options: ["An inventory management system", "A financial modeling technique", "A tool to analyze Political, Economic, Social, Technological, Legal, and Environmental factors", "A human resources recruitment strategy"], correctAnswerIndex: 2 },
      { text: "What is the best description or definition of: Delegation?", options: ["The centralization of all decision-making power", "The process of firing a subordinate", "The assignment of authority to another person to carry out specific activities", "The refusal to complete a task"], correctAnswerIndex: 2 },
      { text: "What is the best description or definition of: Corporate Social Responsibility (CSR)?", options: ["The legal obligation to maximize shareholder wealth", "A strategy to minimize corporate taxes", "The process of advertising social media campaigns", "A business model that helps a company be socially accountable to itself, its stakeholders, and the public"], correctAnswerIndex: 3 },
      { text: "What is the best description or definition of: Blue Ocean Strategy?", options: ["Creating a new, uncontested market space that makes competitors irrelevant", "Competing fiercely in an existing, saturated market", "Slashing prices to drive competitors out of business", "Acquiring all competing firms in an industry"], correctAnswerIndex: 0 },
      { text: "Which of the following closely relates to the concept of 'fundamental accounting equation'?", options: ["Assets = Liabilities - Equity", "Revenue = Expenses + Profit", "Cash = Inflows - Outflows", "Assets = Liabilities + Equity"], correctAnswerIndex: 3 },
      { text: "Which of the following closely relates to the concept of 'Return on Investment (ROI)'?", options: ["Total Revenue - Total Expenses", "Net Profit / Cost of Investment", "Total Assets / Total Liabilities", "Gross Profit / Revenue"], correctAnswerIndex: 1 },
      { text: "Which of the following closely relates to the concept of 'Balance Sheet'?", options: ["A snapshot of a company's financial position at a specific point in time", "A projection of future sales", "A record of all cash transactions", "A summary of revenues and expenses over a period"], correctAnswerIndex: 0 },
      { text: "Which of the following closely relates to the concept of 'Income Statement'?", options: ["A breakdown of operating cash flows", "A record of equity changes", "A summary of revenues and expenses over a period", "A snapshot of assets and liabilities"], correctAnswerIndex: 2 },
      { text: "Which of the following closely relates to the concept of 'Liquidity'?", options: ["The ease with which an asset can be converted into cash", "The market share of a company", "The total amount of debt a company owes", "The profitability of a company over time"], correctAnswerIndex: 0 }
    ],
  },
  "Basic Science & Humanities": {
    "Question Bank": [
      { text: "What is the best description of 'Newton's First Law'?", options: ["For every action, there is an equal and opposite reaction", "Energy cannot be created or destroyed", "Force equals mass times acceleration", "An object at rest stays at rest unless acted upon by a force"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'Velocity'?", options: ["The rate of change of speed", "The mass of an object in motion", "The total distance covered over time", "The rate of change of displacement with respect to time"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'Thermodynamics (First Law)'?", options: ["Heat flows from cold to hot", "Entropy of an isolated system always increases", "Energy can neither be created nor destroyed, only transformed", "Absolute zero cannot be reached"], correctAnswerIndex: 2 },
      { text: "What is the best description of 'Covalent Bond'?", options: ["A bond between two metals", "A bond formed by the transfer of electrons", "An attraction between molecules", "A chemical bond that involves the sharing of electron pairs between atoms"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'pH Scale'?", options: ["A measure of temperature", "A scale for measuring radioactive decay", "A scale for measuring atmospheric pressure", "A measure of the acidity or basicity of an aqueous solution"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'Atomic Number'?", options: ["The atomic weight of an element", "The number of protons in the nucleus of an atom", "The number of electrons in the outer shell", "The total number of protons and neutrons"], correctAnswerIndex: 1 },
      { text: "What is the best description of 'Derivative'?", options: ["A statistical average", "A matrix determinant", "The rate at which a function is changing at any given point", "The area under a curve"], correctAnswerIndex: 2 },
      { text: "What is the best description of 'Integral'?", options: ["The mathematical concept that represents the area under a curve", "The slope of a tangent line", "The rate of change of a function", "The highest point of a parabola"], correctAnswerIndex: 0 },
      { text: "What is the best description of 'Probability'?", options: ["The mean of a data set", "A statistical outlier", "The exact certainty of an event", "The measure of the likelihood that an event will occur"], correctAnswerIndex: 3 },
      { text: "What is the best description of 'Active Voice'?", options: ["A type of academic citation", "A poetic device", "A sentence structure where the subject performs the action stated by the verb", "A sentence where the subject receives the action"], correctAnswerIndex: 2 }
    ],
    "IQ Games": [
      { text: "What is the best description of 'Plagiarism'?", options: ["Paraphrasing with proper attribution", "Citing sources correctly", "The practice of taking someone else's work or ideas and passing them off as one's own", "Working collaboratively on a project"], correctAnswerIndex: 2 },
      { text: "What is the best description of 'Thesis Statement'?", options: ["A list of references", "A short statement that summarizes the main point or claim of an essay or research paper", "The concluding paragraph of an essay", "The abstract of a paper"], correctAnswerIndex: 1 },
      { text: "What is the best description of 'Utilitarianism'?", options: ["An ethical theory based strictly on duty and rules", "The belief that there are no absolute moral rules", "An ethical theory that promotes actions that maximize happiness and well-being for the majority", "The practice of prioritizing individual needs over the group"], correctAnswerIndex: 2 },
      { text: "What is the best description of 'Sociology'?", options: ["The study of economic markets", "The study of the human mind and behavior", "The study of the development, structure, and functioning of human society", "The study of past historical events"], correctAnswerIndex: 2 },
      { text: "What is the best description of 'Epistemology'?", options: ["The branch of philosophy concerned with the theory of knowledge", "The study of moral values", "The study of the physical universe", "The study of beauty and art"], correctAnswerIndex: 0 },
      { text: "Which of the following defines 'Newton's First Law'?", options: ["For every action, there is an equal and opposite reaction", "An object at rest stays at rest unless acted upon by a force", "Energy cannot be created or destroyed", "Force equals mass times acceleration"], correctAnswerIndex: 1 },
      { text: "Which of the following defines 'Velocity'?", options: ["The total distance covered over time", "The rate of change of speed", "The rate of change of displacement with respect to time", "The mass of an object in motion"], correctAnswerIndex: 2 },
      { text: "Which of the following defines 'Thermodynamics (First Law)'?", options: ["Energy can neither be created nor destroyed, only transformed", "Heat flows from cold to hot", "Entropy of an isolated system always increases", "Absolute zero cannot be reached"], correctAnswerIndex: 0 },
      { text: "Which of the following defines 'Covalent Bond'?", options: ["An attraction between molecules", "A chemical bond that involves the sharing of electron pairs between atoms", "A bond between two metals", "A bond formed by the transfer of electrons"], correctAnswerIndex: 1 },
      { text: "Which of the following defines 'pH Scale'?", options: ["A scale for measuring atmospheric pressure", "A measure of the acidity or basicity of an aqueous solution", "A scale for measuring radioactive decay", "A measure of temperature"], correctAnswerIndex: 1 }
    ],
    "Career Questions": [
      { text: "Which of the following defines 'Atomic Number'?", options: ["The number of electrons in the outer shell", "The total number of protons and neutrons", "The number of protons in the nucleus of an atom", "The atomic weight of an element"], correctAnswerIndex: 2 },
      { text: "Which of the following defines 'Derivative'?", options: ["The area under a curve", "A matrix determinant", "The rate at which a function is changing at any given point", "A statistical average"], correctAnswerIndex: 2 },
      { text: "Which of the following defines 'Integral'?", options: ["The rate of change of a function", "The mathematical concept that represents the area under a curve", "The slope of a tangent line", "The highest point of a parabola"], correctAnswerIndex: 1 },
      { text: "Which of the following defines 'Probability'?", options: ["The measure of the likelihood that an event will occur", "The exact certainty of an event", "The mean of a data set", "A statistical outlier"], correctAnswerIndex: 0 },
      { text: "Which of the following defines 'Active Voice'?", options: ["A poetic device", "A sentence structure where the subject performs the action stated by the verb", "A sentence where the subject receives the action", "A type of academic citation"], correctAnswerIndex: 1 },
      { text: "Which of the following defines 'Plagiarism'?", options: ["Citing sources correctly", "Working collaboratively on a project", "The practice of taking someone else's work or ideas and passing them off as one's own", "Paraphrasing with proper attribution"], correctAnswerIndex: 2 },
      { text: "Which of the following defines 'Thesis Statement'?", options: ["The concluding paragraph of an essay", "The abstract of a paper", "A list of references", "A short statement that summarizes the main point or claim of an essay or research paper"], correctAnswerIndex: 3 },
      { text: "Which of the following defines 'Utilitarianism'?", options: ["The practice of prioritizing individual needs over the group", "An ethical theory that promotes actions that maximize happiness and well-being for the majority", "An ethical theory based strictly on duty and rules", "The belief that there are no absolute moral rules"], correctAnswerIndex: 1 },
      { text: "Which of the following defines 'Sociology'?", options: ["The study of economic markets", "The study of the human mind and behavior", "The study of the development, structure, and functioning of human society", "The study of past historical events"], correctAnswerIndex: 2 },
      { text: "Which of the following defines 'Epistemology'?", options: ["The study of the physical universe", "The study of beauty and art", "The branch of philosophy concerned with the theory of knowledge", "The study of moral values"], correctAnswerIndex: 2 }
    ],
  },
  "Computer Sciences": {
    "Question Bank": [
      { text: "What is the best definition of 'Array'?", options: ["A non-linear data structure", "A Last-In-First-Out (LIFO) structure", "A First-In-First-Out (FIFO) structure", "A collection of items stored at contiguous memory locations"], correctAnswerIndex: 3 },
      { text: "What is the best definition of 'Linked List'?", options: ["A database table", "A collection of items stored at contiguous memory locations", "A tree-like structure", "A linear collection of data elements whose order is not given by their physical placement in memory"], correctAnswerIndex: 3 },
      { text: "What is the best definition of 'Stack'?", options: ["A graph without cycles", "A First-In-First-Out (FIFO) data structure", "A Last-In-First-Out (LIFO) data structure", "A relational database model"], correctAnswerIndex: 2 },
      { text: "What is the best definition of 'Queue'?", options: ["A Last-In-First-Out (LIFO) data structure", "A First-In-First-Out (FIFO) data structure", "A hierarchical data model", "A network routing protocol"], correctAnswerIndex: 1 },
      { text: "What is the best definition of 'Binary Tree'?", options: ["A linear data structure", "A tree data structure in which each node has at most two children", "A collection of nodes with no edges", "A graph with multiple cycles"], correctAnswerIndex: 1 },
      { text: "What is the best definition of 'Binary Search'?", options: ["An algorithm used only for string matching", "An algorithm that checks every single item sequentially", "A sorting algorithm with O(n^2) complexity", "An efficient algorithm for finding an item from a sorted list of items"], correctAnswerIndex: 3 },
      { text: "What is the best definition of 'Quick Sort'?", options: ["A divide-and-conquer algorithm that picks an element as a pivot and partitions the given array around it", "An algorithm for finding the shortest path in a graph", "An encryption algorithm", "A sorting algorithm that repeatedly swaps adjacent elements"], correctAnswerIndex: 0 },
      { text: "What is the best definition of 'Merge Sort'?", options: ["A dynamic programming algorithm for strings", "An algorithm that sorts by inserting elements one by one into their correct position", "A greedy algorithm", "A divide-and-conquer algorithm that divides the input array into two halves, calls itself for the two halves, and then merges the two sorted halves"], correctAnswerIndex: 3 },
      { text: "What is the best definition of 'Dijkstra's Algorithm'?", options: ["A fast sorting algorithm", "An algorithm for finding the shortest paths between nodes in a graph", "A hashing function", "An algorithm to find the maximum flow in a network"], correctAnswerIndex: 1 },
      { text: "What is the best definition of 'Dynamic Programming'?", options: ["A network routing method", "An object-oriented design pattern", "An algorithmic technique for solving an optimization problem by breaking it down into simpler subproblems", "A method of writing programs while they are running"], correctAnswerIndex: 2 }
    ],
    "IQ Games": [
      { text: "What is the best definition of 'Process'?", options: ["A type of network cable", "A permanent storage device", "A program in execution", "A physical piece of hardware"], correctAnswerIndex: 2 },
      { text: "What is the best definition of 'Thread'?", options: ["A complete running application", "A file system structure", "The smallest sequence of programmed instructions that can be managed independently by a scheduler", "A block of memory"], correctAnswerIndex: 2 },
      { text: "What is the best definition of 'Deadlock'?", options: ["A state where the CPU is idle", "A situation where a set of processes are blocked because each process is holding a resource and waiting for another resource acquired by some other process", "A hardware failure", "A memory leak"], correctAnswerIndex: 1 },
      { text: "What is the best definition of 'Virtual Memory'?", options: ["A read-only memory component", "A CPU cache", "A physical RAM chip", "A memory management capability that provides an idealized abstraction of the storage resources that are actually available"], correctAnswerIndex: 3 },
      { text: "What is the best definition of 'Context Switching'?", options: ["The process of storing and restoring the state of a process or thread so that execution can be resumed from the same point", "Connecting to a different network", "Switching between different programming languages", "Changing the physical CPU"], correctAnswerIndex: 0 },
      { text: "What is the best definition of 'IP Address'?", options: ["A domain name", "A physical hardware address embedded in a network card", "A secure protocol for sending emails", "A numerical label assigned to each device connected to a computer network"], correctAnswerIndex: 3 },
      { text: "What is the best definition of 'MAC Address'?", options: ["A routing protocol", "A unique identifier assigned to a network interface controller (NIC) for use as a network address", "An application layer protocol", "A temporary IP address"], correctAnswerIndex: 1 },
      { text: "What is the best definition of 'TCP (Transmission Control Protocol)'?", options: ["A connectionless protocol with no guarantee of delivery", "A protocol for web browsing only", "A protocol for assigning IP addresses", "A connection-oriented protocol that ensures reliable and ordered delivery of a stream of bytes"], correctAnswerIndex: 3 },
      { text: "What is the best definition of 'UDP (User Datagram Protocol)'?", options: ["A connection-oriented protocol that ensures reliable delivery", "A secure file transfer protocol", "A connectionless protocol that sends messages with a minimum of protocol mechanism", "A database query language"], correctAnswerIndex: 2 },
      { text: "What is the best definition of 'DNS (Domain Name System)'?", options: ["A physical server that stores all internet data", "A protocol for encrypting network traffic", "A hierarchical and decentralized naming system for computers, services, or other resources connected to the Internet", "A routing algorithm for internal networks"], correctAnswerIndex: 2 }
    ],
    "Career Questions": [
      { text: "Which of the following statements correctly describes 'Array'?", options: ["A First-In-First-Out (FIFO) structure", "A Last-In-First-Out (LIFO) structure", "A collection of items stored at contiguous memory locations", "A non-linear data structure"], correctAnswerIndex: 2 },
      { text: "Which of the following statements correctly describes 'Linked List'?", options: ["A collection of items stored at contiguous memory locations", "A tree-like structure", "A linear collection of data elements whose order is not given by their physical placement in memory", "A database table"], correctAnswerIndex: 2 },
      { text: "Which of the following statements correctly describes 'Stack'?", options: ["A First-In-First-Out (FIFO) data structure", "A relational database model", "A Last-In-First-Out (LIFO) data structure", "A graph without cycles"], correctAnswerIndex: 2 },
      { text: "Which of the following statements correctly describes 'Queue'?", options: ["A Last-In-First-Out (LIFO) data structure", "A network routing protocol", "A First-In-First-Out (FIFO) data structure", "A hierarchical data model"], correctAnswerIndex: 2 },
      { text: "Which of the following statements correctly describes 'Binary Tree'?", options: ["A graph with multiple cycles", "A collection of nodes with no edges", "A linear data structure", "A tree data structure in which each node has at most two children"], correctAnswerIndex: 3 },
      { text: "Which of the following statements correctly describes 'Binary Search'?", options: ["A sorting algorithm with O(n^2) complexity", "An algorithm used only for string matching", "An algorithm that checks every single item sequentially", "An efficient algorithm for finding an item from a sorted list of items"], correctAnswerIndex: 3 },
      { text: "Which of the following statements correctly describes 'Quick Sort'?", options: ["A divide-and-conquer algorithm that picks an element as a pivot and partitions the given array around it", "An encryption algorithm", "An algorithm for finding the shortest path in a graph", "A sorting algorithm that repeatedly swaps adjacent elements"], correctAnswerIndex: 0 },
      { text: "Which of the following statements correctly describes 'Merge Sort'?", options: ["A greedy algorithm", "A dynamic programming algorithm for strings", "An algorithm that sorts by inserting elements one by one into their correct position", "A divide-and-conquer algorithm that divides the input array into two halves, calls itself for the two halves, and then merges the two sorted halves"], correctAnswerIndex: 3 },
      { text: "Which of the following statements correctly describes 'Dijkstra's Algorithm'?", options: ["A hashing function", "An algorithm for finding the shortest paths between nodes in a graph", "An algorithm to find the maximum flow in a network", "A fast sorting algorithm"], correctAnswerIndex: 1 },
      { text: "Which of the following statements correctly describes 'Dynamic Programming'?", options: ["An object-oriented design pattern", "A network routing method", "A method of writing programs while they are running", "An algorithmic technique for solving an optimization problem by breaking it down into simpler subproblems"], correctAnswerIndex: 3 }
    ],
  },
  "Software Engineering": {
    "Question Bank": [
      { text: "What does HTML stand for?", options: ["HyperText Markup Language", "High Technology Modern Language", "HyperText Modern Links", "High Text Markup Language"], correctAnswerIndex: 0 },
      { text: "Which symbol is used for single-line comments in Python?", options: ["//", "#", "/*", "--"], correctAnswerIndex: 1 },
      { text: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"], correctAnswerIndex: 0 },
      { text: "Which data structure follows LIFO order?", options: ["Queue", "Array", "Stack", "Linked List"], correctAnswerIndex: 2 },
      { text: "What is the binary representation of decimal 10?", options: ["1010", "1100", "1001", "1110"], correctAnswerIndex: 0 },
      { text: "Which language is primarily used for styling web pages?", options: ["HTML", "JavaScript", "CSS", "PHP"], correctAnswerIndex: 2 },
      { text: "What does OOP stand for?", options: ["Object-Oriented Programming", "Open Online Processing", "Ordered Object Protocol", "Output Oriented Programming"], correctAnswerIndex: 0 },
      { text: "Which of these is a version control system?", options: ["Docker", "Git", "Jira", "Slack"], correctAnswerIndex: 1 },
      { text: "What is the time complexity of binary search?", options: ["O(n)", "O(n²)", "O(log n)", "O(1)"], correctAnswerIndex: 2 },
      { text: "Which keyword is used to declare a variable in JavaScript?", options: ["var", "int", "dim", "define"], correctAnswerIndex: 0 }
    ],
    "IQ Games": [
      { text: "What does SQL stand for?", options: ["Structured Query Language", "Simple Question Language", "System Query Logic", "Structured Question List"], correctAnswerIndex: 0 },
      { text: "Which data structure uses FIFO order?", options: ["Stack", "Queue", "Tree", "Graph"], correctAnswerIndex: 1 },
      { text: "What is the default port for HTTP?", options: ["443", "21", "80", "8080"], correctAnswerIndex: 2 },
      { text: "Which operator checks both value and type in JavaScript?", options: ["==", "!=", "===", "="], correctAnswerIndex: 2 },
      { text: "What does RAM stand for?", options: ["Read Access Memory", "Random Access Memory", "Rapid Application Memory", "Read And Memorize"], correctAnswerIndex: 1 },
      { text: "In Python, which function prints output to the screen?", options: ["echo()", "console.log()", "print()", "write()"], correctAnswerIndex: 2 },
      { text: "What is an algorithm?", options: ["A programming language", "A set of instructions to solve a problem", "A type of database", "A hardware component"], correctAnswerIndex: 1 },
      { text: "Which of these is NOT a programming paradigm?", options: ["Object-Oriented", "Functional", "Procedural", "Sequential Filing"], correctAnswerIndex: 3 },
      { text: "What does IDE stand for?", options: ["Integrated Development Environment", "Internal Debug Engine", "Internet Development Extension", "Integrated Debug Editor"], correctAnswerIndex: 0 },
      { text: "Which HTML tag creates a hyperlink?", options: ["<link>", "<href>", "<a>", "<url>"], correctAnswerIndex: 2 }
    ],
    "Career Questions": [
      { text: "What is the main purpose of an operating system?", options: ["Run browsers", "Manage hardware and software resources", "Write code", "Store files only"], correctAnswerIndex: 1 },
      { text: "Which of the following is a relational database?", options: ["MongoDB", "Redis", "MySQL", "Cassandra"], correctAnswerIndex: 2 },
      { text: "What does API stand for?", options: ["Application Programming Interface", "Automated Program Integration", "Application Protocol Index", "Applied Programming Input"], correctAnswerIndex: 0 },
      { text: "Which sorting algorithm is the simplest to implement?", options: ["Quick Sort", "Merge Sort", "Bubble Sort", "Heap Sort"], correctAnswerIndex: 2 },
      { text: "What is a variable in programming?", options: ["A fixed value", "A named storage location for data", "A type of loop", "A function"], correctAnswerIndex: 1 },
      { text: "Which protocol is used to send emails?", options: ["HTTP", "FTP", "SMTP", "SSH"], correctAnswerIndex: 2 },
      { text: "What does 'localhost' refer to?", options: ["A remote server", "The current machine you are working on", "A DNS server", "A cloud service"], correctAnswerIndex: 1 },
      { text: "What is an array?", options: ["A single data value", "A collection of elements of the same type", "A type of function", "A database table"], correctAnswerIndex: 1 },
      { text: "What is the purpose of a compiler?", options: ["Run programs directly", "Convert source code to machine code", "Debug errors", "Manage memory"], correctAnswerIndex: 1 },
      { text: "Which symbol denotes a class in a UML diagram?", options: ["Circle", "Diamond", "Rectangle", "Triangle"], correctAnswerIndex: 2 }
    ],
  },
};
